openapi: 3.0.0
info:
  title: Nearest Path Service
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/nearest-path:
    post:
      summary: Find the nearest path based on coordinates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                latitude:
                  type: number
                  example: -6.200000
                longitude:
                  type: number
                  example: 106.816666
      responses:
        '200':
          description: Nearest location found
          content:
            application/json:
              schema:
                type: object
                properties:
                  province:
                    type: string
                  district:
                    type: string
                  sub_district:
                    type: string
                  village:
                    type: string
                  border:
                    type: array
                    items:
                      type: array
                      items:
                        type: number
        '404':
          description: No nearby location found
        '400':
          description: Invalid input data
